from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REFERENCES_DIR = ROOT / "references"
OUTPUT_PATH = REFERENCES_DIR / "_index.md"
CATEGORY_ORDER = [
    "appsec",
    "infra",
    "iam",
    "platform",
    "ai",
    "privacy",
    "ops",
    "compliance",
]


def parse_frontmatter(path: Path) -> dict:
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines or lines[0].strip() != "---":
        raise ValueError(f"{path} is missing YAML frontmatter")

    data: dict[str, object] = {}
    i = 1
    while i < len(lines):
        line = lines[i]
        if line.strip() == "---":
            break

        if not line.strip():
            i += 1
            continue

        if ":" not in line:
            raise ValueError(f"Unsupported frontmatter line in {path}: {line}")

        key, raw_value = line.split(":", 1)
        key = key.strip()
        raw_value = raw_value.strip()

        if raw_value == "":
            items: list[str] = []
            i += 1
            while i < len(lines):
                nested = lines[i]
                if nested.strip() == "---":
                    i -= 1
                    break
                if not nested.startswith("  - "):
                    i -= 1
                    break
                item = nested[4:].strip()
                if item.startswith('"') and item.endswith('"'):
                    item = json.loads(item)
                items.append(item)
                i += 1
            data[key] = items
        elif raw_value == "null":
            data[key] = None
        elif raw_value.startswith("["):
            data[key] = json.loads(raw_value)
        elif raw_value.startswith('"') and raw_value.endswith('"'):
            data[key] = json.loads(raw_value)
        elif raw_value.isdigit():
            data[key] = int(raw_value)
        else:
            data[key] = raw_value

        i += 1

    return data


def audit_levels(value: object) -> str:
    if not isinstance(value, list):
        return "-"
    return ", ".join(str(item) for item in value)


def reviewed(value: object) -> str:
    return "stale" if value is None else str(value)


def collect_entries() -> dict[str, list[dict]]:
    grouped = {category: [] for category in CATEGORY_ORDER}
    for path in sorted(REFERENCES_DIR.rglob("*.md")):
        if path.name == "_index.md":
            continue
        if path.parent == REFERENCES_DIR:
            raise ValueError(f"{path} still lives at the flat root of references/")

        meta = parse_frontmatter(path)
        category = str(meta["category"])
        if category not in grouped:
            raise ValueError(f"{path} has unsupported category {category}")

        grouped[category].append(
            {
                "title": meta["title"],
                "slug": meta["slug"],
                "depth": meta["depth"],
                "audit_level": meta["audit_level"],
                "last_reviewed": meta["last_reviewed"],
                "path": path.relative_to(ROOT).as_posix(),
            }
        )

    for category in grouped:
        grouped[category].sort(key=lambda item: str(item["title"]).lower())

    return grouped


def build_index() -> str:
    grouped = collect_entries()
    total = sum(len(items) for items in grouped.values())

    out: list[str] = []
    out.append("# Reference Index")
    out.append("")
    out.append("> Auto-generated by `scripts/build-index.py`. Do not edit by hand.")
    out.append("")
    out.append(f"- Total references: {total}")
    out.append(f"- Categories: {len(CATEGORY_ORDER)}")
    out.append("")
    out.append("## Category Summary")
    out.append("")
    out.append("| Category | Files |")
    out.append("|---|---:|")
    for category in CATEGORY_ORDER:
        out.append(f"| `{category}` | {len(grouped[category])} |")
    out.append("")

    for category in CATEGORY_ORDER:
        out.append(f"## {category}")
        out.append("")
        out.append("| Title | Slug | Depth | Audit levels | Reviewed | Path |")
        out.append("|---|---|---:|---|---|---|")
        for entry in grouped[category]:
            out.append(
                "| {title} | `{slug}` | {depth} | `{audit}` | {reviewed} | `{path}` |".format(
                    title=entry["title"],
                    slug=entry["slug"],
                    depth=entry["depth"],
                    audit=audit_levels(entry["audit_level"]),
                    reviewed=reviewed(entry["last_reviewed"]),
                    path=entry["path"],
                )
            )
        out.append("")

    return "\n".join(out).rstrip() + "\n"


def main() -> None:
    OUTPUT_PATH.write_text(build_index(), encoding="utf-8")


if __name__ == "__main__":
    main()
